import { Prize } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import { useState, useEffect } from "react";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const [fetchedPrizes, setFetchedPrizes] = useState<Prize[]>([]);
  const [prize, setPrize] = useState<Prize>();
  const [hasPlayed, setHasPlayed] = useState(false);
  const [hasCopied, setHasCopied] = useState(false);
  const [won, setWon] = useState(false);

  const localStorageData =
    typeof window !== "undefined" ? localStorage.getItem("results") ?? "" : "";

  useEffect(() => {
    if (localStorageData === "") return;
    setHasPlayed(true);
    const data = JSON.parse(localStorageData);
    if (data !== "lost") {
      setPrize(data);
      setWon(true);
    }
  }, [localStorageData]);

  const fetchPrizes = api.prizes.getAllAvailablePrizes.useQuery(undefined, {
    onSuccess: (prizes) => {
      setFetchedPrizes(prizes.filter((prize) => prize.count > 0));
    },
    refetchInterval: 100,
    enabled: !hasPlayed,
  });

  const updatePrizeCount = api.prizes.updatePrizesCountById.useMutation();

  function handleGenerate(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setHasPlayed(true);

    const possible = [...fetchedPrizes, "lost"];

    const result = possible[Math.floor(Math.random() * possible.length)] as
      | Prize
      | "lost";

    if (result !== "lost") {
      updatePrizeCount
        .mutateAsync({
          id: result.id,
          count: result.count - 1,
        })
        .then((prize) => setPrize(prize));
      setPrize(result);
    }
    localStorage.setItem("results", JSON.stringify(result));
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-6 bg-gradient-to-b from-[#2e026d] to-[#15162c] text-2xl text-white">
        {fetchPrizes.isLoading ? (
          <p>Loading...</p>
        ) : !fetchedPrizes.length ? (
          <p>Raffle Over</p>
        ) : hasPlayed ? (
          won ? (
            prize && (
              <>
                <p>{prize.name}</p>
                <div className="flex gap-4 justify-center items-center">
                  <p>{prize.id}</p>
                  <button
                    onClick={() => {
                      setHasCopied(true);
                      navigator.clipboard.writeText(prize.id);
                    }}
                    className="py-2 px-5 font-semibold no-underline rounded-lg transition bg-white/10 hover:bg-white/20"
                  >
                    {hasCopied ? "Copied" : "Copy"}
                  </button>
                </div>
              </>
            )
          ) : (
            <p>You Lost</p>
          )
        ) : (
          <form onSubmit={handleGenerate}>
            <button className="py-3 px-10 font-semibold no-underline rounded-full transition bg-white/10 hover:bg-white/20">
              Generate
            </button>
          </form>
        )}
      </main>
    </>
  );
};

export default Home;
